name: Jekyll Site Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1 # Specify the Ruby version

    - name: Install Jekyll and dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the Jekyll site
      run: bundle exec jekyll build

