apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
  - name: cleanup
    image: alpine
    script: |
      #!/bin/sh
      echo "Cleaning up resources..."
      # Add cleanup logic here

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  steps:
  - name: run-nose-tests
    image: python:3.9
    workingDir: /workspace/source
    script: |
      #!/bin/sh
      pip install nose
      pip install -r requirements.txt
      nosetests tests/