name: Linting with flake8

# Trigger the workflow on pushes and pull requests to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace '3.x' with the specific version (e.g., '3.8')

      # Step 3: Install dependencies, including flake8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Step 4: Run flake8 to lint the code
      - name: Lint with flake8
        run: |
          flake8 .
